# Generated by Django 2.2 on 2020-01-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Type',
        ),
    ]
