# Generated by Django 3.0.2 on 2020-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='dashboard'),
        ),
    ]
