# Generated by Django 3.0.2 on 2020-02-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='end_date',
        ),
    ]
