# Generated by Django 3.0.2 on 2020-02-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_bookings_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
