# Generated by Django 3.0.2 on 2020-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.NullBooleanField(default=1, max_length=5, verbose_name='Availability status'),
        ),
    ]
