# Generated by Django 3.0.2 on 2020-02-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_bookings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='urlhash',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Service', verbose_name='Reference Code'),
        ),
    ]
