# Generated by Django 3.0.2 on 2020-02-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200217_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='attachment',
        ),
    ]
