# Generated by Django 3.0.2 on 2020-02-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_service_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.NullBooleanField(default=0, max_length=5, verbose_name='Payment status'),
        ),
    ]
