# Generated by Django 3.0.2 on 2020-02-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_bookings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='mpesa_receipt_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
