# Generated by Django 3.0.2 on 2020-02-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_bookings_mpesa_receipt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
