# Generated by Django 3.0.2 on 2020-02-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20200226_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
