# Generated by Django 3.0.2 on 2020-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_delete_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
