# Generated by Django 2.2.3 on 2019-08-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190827_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Executive', 'Executive'), ('System Admin', 'System Admin'), ('Public Transport', 'Public Transport'), ('County Public Service Board', 'County Public Service Board'), ('Water And Environment', 'Water And Environment'), ('Education And Sports', 'Education And Sports'), ('Trade', 'Trade'), ('Agriculture', 'Agriculture'), ('Public Administration', 'Public Administration'), ('Gender And Social Services', 'Gender And Social Services'), ('Health', 'Health'), ('Economic Planning', 'Economic Planning'), ('Lands And Housing', 'Lands And Housing'), ('Finance', 'Finance'), ('County Secretary', 'County Secretary'), ('Governor And Deputy Governor', 'Governor And Deputy Governor')], max_length=254, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
