# Generated by Django 2.2 on 2019-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='A little info about yourself'),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Select your skillset here:'),
        ),
    ]
