# Generated by Django 2.2 on 2020-01-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Skillset'),
        ),
    ]
